### ISSUE TITLE
Setup not working because of a circular dependency

### ISSUE THREAD

**Issue by lucagiove** [robotframework-thailand/robotframework-redislibrary#11]
If you try to install using the git repository it won't work because of the setup.py bug:

```
pip install git+https://github.com/nottyo/robotframework-redislibrary.git@0.2#egg=robotframework-redislibrary
Collecting robotframework-redislibrary from git+https://github.com/nottyo/robotframework-redislibrary.git@0.2#egg=robotframework-redislibrary
  Cloning https://github.com/chilispa/robotframework-redislibrary.git (to revision 0.2) to /tmp/pip-install-65rw3h47/robotframework-redislibrary
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-65rw3h47/robotframework-redislibrary/setup.py", line 5, in <module>
        from RedisLibrary.version import VERSION
      File "/tmp/pip-install-65rw3h47/robotframework-redislibrary/RedisLibrary/__init__.py", line 2, in <module>
        from .RedisLibraryKeywords import RedisLibraryKeywords
      File "/tmp/pip-install-65rw3h47/robotframework-redislibrary/RedisLibrary/RedisLibraryKeywords.py", line 2, in <module>
        from robot.api import logger
    ModuleNotFoundError: No module named 'robot'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-65rw3h47/robotframework-redislibrary/
```

It can be reproduced directly installing on the setup (with a clean virtualenv)

```
luca@elite:~/src/robotframework-redislibrary$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from RedisLibrary.version import VERSION
  File "/home/luca/src/chili/aquaman/robotframework-redislibrary/RedisLibrary/__init__.py", line 2, in <module>
    from .RedisLibraryKeywords import RedisLibraryKeywords
  File "/home/luca/src/chili/aquaman/robotframework-redislibrary/RedisLibrary/RedisLibraryKeywords.py", line 2, in <module>
    from robot.api import logger
ModuleNotFoundError: No module named 'robot'
```

**Comment by ecarmiel** [comment]
Hi
i'm still having this issue .
is there another version where this is fixed ?
Collecting robotframework-redislibrary-xwfintech
  Downloading https://files.pythonhosted.org/packages/c3/80/30df52d580a0d4781c5a22734c58471463cc4d97be3701b42cabfcaf66e3/robotframework-redislibrary-xwfintech-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pycharm-packaging/robotframework-redislibrary-xwfintech/setup.py", line 5, in <module>
        from RedisLibrary.version import VERSION
      File "/tmp/pycharm-packaging/robotframework-redislibrary-xwfintech/RedisLibrary/__init__.py", line 2, in <module>
        from .RedisLibraryKeywords import RedisLibraryKeywords
      File "/tmp/pycharm-packaging/robotframework-redislibrary-xwfintech/RedisLibrary/RedisLibraryKeywords.py", line 5, in <module>
        import redis
    ModuleNotFoundError: No module named 'redis'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pycharm-packaging/robotframework-redislibrary-xwfintech/

**Comment by ecarmiel** [comment]
Hi this is still happening . isn't there a fix for it ?

**Comment by lucagiove** [comment]
I fixed in the pull request but nobody merged it :(
I now removed the new keyword and created a new pull request only for fixes I hope @nottyo will integrate it soon.

**Comment by lucagiove** [comment]
In your case by the way you could fix just by installing redis before with `pip install redis`

**Comment by lucagiove** [comment]
Finally PR got merged
